sudo: false

language: node_js

node_js:
  - "stable"

after_success:
  - npm run coveralls

addons:
  postgresql: "11"

  before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - npm run migrate