# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  print_hello:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run: echo world
  print_env:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run:
          name: 'an env var that is part of the project'
          command: |
            echo $my_name

  save_on_file:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run: echo "Hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_env
      - save_on_file
      - print_output_file:
          requires:
            - save_on_file
